### PR TITLE
Python 2.6 test fix and travis ci

### PR DESCRIPTION
**Pull request by nelsonjchen**
This encompasses #39 and #40 with the "addition" of removing Python 2.6 from the list of allowed failures. Merging this in will close those too.

### CODE REVIEW

**Comment by nelsonjchen** [comment]
Looks superceded. Closing.

**Comment by nelsonjchen** [comment]
Actually, this pull request re enables 2.6 as an allowed failure.

**Comment by nelsonjchen** [comment]
I meant not allowed failure.

**Comment by madzak** [comment]
Yeah I was in the middle of accepting it, didn't realize you rolled it all up :)

**Comment by madzak** [comment]
Thanks for the big update and adding Travis support!

**Comment by nelsonjchen** [comment]
Actually, I don't think I did all that much. I just saw a CI folder or
commit but no CI and some decent tests. It's just a small change to make
sure the large additions and swaths of test code, which aren't part of this
or authored by me, are run.

On Sat, Feb 25, 2017, 12:13 PM Zakaria Zajac <notifications@github.com>
wrote:

Thanks for the big update and adding Travis support!

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/madzak/python-json-logger/pull/41#issuecomment-282509241>,
or mute the thread

**Comment by madzak** [comment]
I still appreciate the contribution. Thanks again!

**Pull request merged**
