### PR TITLE
Update examples and tests for Python 3.8 compatibility

### PR DESCRIPTION
**Pull request by tommilligan**
See #86 
See #74 

This PR fixes up a couple of small issues encountered when upgrading to Python 3.8:
- updates examples in `README.md` to be compatible with Python 3.8
- updates test code to match the formatting example provided in the readme
- adds Python 3.8 testing to Travis and tox
- marks the package as Python 3.8 compatible in `setup.py`

### CODE REVIEW

**Comment by the-wondersmith** [comment]
Would love to see this available in the mainline PyPi package

**Comment by tommilligan** [comment]
@madzak is there anything else I can do to help this into master?

**Comment by browniebroke** [comment]
Had the same issue, and this made the trick, thanks @tommilligan! 👍

**Comment by madzak** [comment]
Hi terribly sorry for the HUGE delay but i really appreciate you adding 3.8!

**Pull request merged**
